apiVersion: v1
kind: PersistentVolume
metadata:
  name: postrges-volume
  labels:
    type: local
spec:
  storageClassName: postrges-volume
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/postrges"

